### ISSUE TITLE
By aligning items to center carousel crops images

### ISSUE THREAD

**Issue by Thunderer0** [Learus/react-material-ui-carousel#139]
in version 2.3.1
![previous version](https://user-images.githubusercontent.com/76218241/147045378-acb1caed-5faa-423f-a74c-7096fc85a706.png)

in current version
![latest version](https://user-images.githubusercontent.com/76218241/147045476-8e170c7d-1a2a-40d7-a3da-adf01d20139b.png)

These are results with same piece of code but different versions

**Comment by Learus** [comment]
Hello. Would you be able to share the code that has this problem? A CodeSandbox would be appreciated.

**Comment by Thunderer0** [comment]
`         <div className="ProductDetails">
            <div>
              <Carousel>
                {product.images &&
                  product.images.map((item, i) => (
                    <img
                      className="CarouselImage"
                      key={i}
                      src={item.url}
                      alt={`${i} Slide`}
                    />
                  ))}
              </Carousel>
            </div>
          </div>` 
This was the react code 
.ProductDetails>div {
    width: 100%;
    display: flex;
    flex-direction: column;
    justify-content: space-evenly;
    **align-items: center;**
    padding: 2vmax;
    box-sizing: border-box;
    border: 1px solid white;
}
and this was it's css 
by simply changing version of Carousel my output was changed so I don't think so there would be any problem with code

**Comment by Learus** [comment]
Any specific frameworks used, other than `react`? I'm referring to stuff like `Nextjs`, `Gatsby` or something similar.

**Comment by Thunderer0** [comment]
No I've only used react

**Comment by Learus** [comment]
[This is the sandbox I used to test](https://codesandbox.io/s/distracted-dhawan-9vsc4?file=/src/App.js:181-184)

This is the css you should be using here:
```css
.ProductDetails {
  display: flex;
  flex-direction: column;
  justify-content: space-evenly;
  align-items: center;
  padding: 2vmax;
  border: 1px solid white;
}

.ProductDetails > div {
  width: 100%;
}
```

**Comment by Thunderer0** [comment]
I used sandbox but I guess it has same error image is cropped
![ans](https://user-images.githubusercontent.com/76218241/147062701-a4bd0852-c277-4a4b-a2b1-3a47c3d21f23.png)

but after opening console full image was there😅
![ans 2](https://user-images.githubusercontent.com/76218241/147064255-17b1e2d8-fc79-4e7b-8efd-71bd81234e14.png)

**Comment by Learus** [comment]
This issue should be fixed in v3.3.3 onwards, as long as the tests I did were similar to your environment.

The carousel's height now dynamically changes to be exactly the currently active child's height. You can override this behavior by specifying the `height` prop.

**Comment by BilawalArif** [comment]
![carouser](https://user-images.githubusercontent.com/99284913/225660334-c3612b0e-e2e1-4f6e-aeb9-66f1fd467868.PNG)
I am still having the same issue.
    "react-material-ui-carousel": "^3.4.2",
this is my version.

```
<div className="ProductDetails">
        <div>
          <Carousel>
            {product.images &&
              product.images.map((item, i) => (
                <img 
                  className="CarouselImage"
                  key={item.url}
                  src={item.url}
                  alt={`${i} Slide`}
                />
              ))}
          </Carousel>
</div>
``` 


here is the code

```
.ProductDetails {
    background-color: rgb(205, 202, 202);
    width: 100vw ;
    max-width: 100% ;
    padding: 7vmax;
    box-sizing: border-box;
    justify-content: space-evenly;
    display: flex ;
    
  }
```
